### ISSUE TITLE
Issue with Stylesheets

### ISSUE THREAD

**Issue by lou** [KieferSivitz/vue-gh-pages#10]
I have an issue with the CSS file.
It is looking for
`https://username.github.io/static/css/app.hash.css`
instead of
`https://username.github.io/project/static/css/app.hash.css`

Did I miss something here ?

**Comment by KieferSivitz** [comment]
Just want to make sure before I close this, it's resolved?

**Comment by lou** [comment]
Yes thanks to https://github.com/KieferSivitz/vue-gh-pages/pull/11
Thank you
