### ISSUE TITLE
svg not found (relative path)

### ISSUE THREAD

**Issue by Kawue** [KieferSivitz/vue-gh-pages#18]
The relative path of my svg "../assets/image.svg" is relinked to "/static/img/image.aef2462.png" on gh pages. This results into image not found as it needs to be "./static/img/image.aef2462.png". Can I rewrite the mapping somehow? I did not found the correct place where its done.

**Comment by Kawue** [comment]
No problem, grateful you implemented the whole stuff.

The path is part of a src, in fact it looks like:
`<img src="../assets/image.svg" alt="Image">`

If I change the path as mentioned above manually within the browser inspector and adjust the width property it works.

**Comment by Kawue** [comment]
Before I forget it. I tried to change the path manually within the generated files. But instead of 
./static/img/image.aef2462.png the path will become
/./static/img/image.aef2462.png so there is always this forward slash, which prevents that the image can be found. Don't know if this is a problem on Githubs side or yours.

**Comment by KieferSivitz** [comment]
If this is using the webpack-simple template, today's update (1.12.0) might fix this. There are new instructions on the readme for this template specifically. I believe the part about changing the webpack.config publicPath should resolve this. 

Let me know if it does not and I'll investigate further

**Comment by KieferSivitz** [comment]
Is this img tag in the index.html after the build or is it a child of the 'app' div (that vue puts all it's files inside) when you view the page ?

**Comment by Kawue** [comment]
It is a child of the app div. Have not tested the commited fix, since I solved the problem by adding:
`publicPath: './'` into the  `output{...}` object of the webpack.prod.conf.js file.

I could take a view on the fix at the weekend.

**Comment by KieferSivitz** [comment]
That was actually what I was going to suggest. Anything inside the index.html can be reached by this module. Any paths that are broken inside the app div are created during the build and managed by the webpack.config.

Now that this is confirmed to be the case, I will add this information to the README to hopefully prevent anyone from running into this moving forward.

Thank you
