### ISSUE TITLE
Shouldn't it also actually sync the prepared build with github?

### ISSUE THREAD

**Issue by holmesworcester** [KieferSivitz/vue-gh-pages#2]
Apologies if this doesn't make sense for some reason; I'm a beginner...

But create-react-app fully automates the flow so that there's no second step of committing and pushing to github. https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages

It seems like this would be super handy to everyone using this. 

Thanks for making this! :)

**Comment by KieferSivitz** [comment]
I honestly just never thought about this. I'll look into it when I get a chance and see if I can get it working.

**Comment by holmesworcester** [comment]
awesome :) thanks!

**Comment by KieferSivitz** [comment]
Alright, version 1.6.0 should include this, the only change needed from anyone currently using it is adding a homepage in package.json that links to the repository (it will work the same as before if there is no homepage added).

I'm going to close this but if there's any issues let me know.
Thanks for the idea, it saves a lot of steps!
