### ISSUE TITLE
Lerna monorepo support?

### ISSUE THREAD

**Issue by timneedham** [KieferSivitz/vue-gh-pages#24]
Hi,

### __Loving `vue-gh-pages`... worked for two projects with no problems!__

__But I've hit a bit of a snag when using it with a [Lerna](https://lernajs.io/) monorepo...__ 

One of our packages (to provide an online Vue-powered "playpen") is defined inside our Lerna monorepo.

* I've added __vue-gh-pages__, to this playpen package and it's done it's thing perfectly
* But as expected the `/docs` folder is created within the **package** directory, ideally in this scenario it would be generated at the **project** route of the monorepo.

* I was wondering if it might be possible to upgrade **vue-gh-pages** to output the `/docs` directory to wherever the `.git` directory is first found (discovered by ascending the parent directories).
* Perhaps adding a `--monorepomode` switch to enable this optionally?
* Or is this a webpack build config thing?

**Any help/thoughts really welcome!**

__And thanks again for the project, really useful!__

Tim

**Comment by timneedham** [comment]
That would be brilliant, thanks for taking a look Kiefer. Tim

**Comment by KieferSivitz** [comment]
So it seemed like the most reasonable solution was to allow you to specify the directory, or path to the directory, you want to output to as a command line argument.

I added instructions to the readme, but essentially:

	node ./node_modules/vue-gh-pages/index.js -o C:\Users\MyUser\Documents\Folder

	node ./node_modules/vue-gh-pages/index.js --output ../DeleteMe

And if you would like to preserve the docs folder after pushing to Github:
Use the command line argument 

	-p

	node ./node_modules/vue-gh-pages/index.js -p

If I misunderstood the problem, and this doesn't actually solve your problem let me know

**Comment by timneedham** [comment]
__Worked absolutely perfectly for me!__

But is `--output` mandatory now though? 

* Without specifying it __vue-gh-pages__ didn't seem to generate anything (i,.e. in the previous default `./docs` directory)... but adding `--output ../../` worked an absolute charm, so thank you very much for that! )

**Comment by KieferSivitz** [comment]
Awesome! 
I think you're right, it looks like it was using the '/docs' folder, rather than the 'docs' folder if it wasn't specified. So it wouldn't copy to the docs folder unless the docs folder already existed (which, the script deletes by default so...) 
This should be fixed now (version 1.15.3), Good catch.
