### ISSUE TITLE
Not able to view site content when deployed to gh-pages

### ISSUE THREAD

**Issue by sushant-j** [KieferSivitz/vue-gh-pages#28]
Hey,
I was trying to use this plugin to deploy my site to gh-pages, but am getting a completely [blank page](https://sushant-j.github.io/portfolio/) when visiting the deployed site.

I realize this might not be an issue with the plugin itself, could be some missing config or similar in my project. But I can't seem to find anything wrong after following all the steps mentioned in your README.

Any help appreciated :)

**Comment by boussadjra** [comment]
do you have vue.config.js file in the project root?

**Comment by sushant-j** [comment]
Hey @boussadjra,
Thanks for your prompt reply! I indeed was missing the vue.config.js file from my setup. I was able to get around this by using `base:` property in router.js.

Closing this issue as resolved.

**Comment by batin** [comment]
I have webpack.config.js but still there is no content? how should i do?? 
[repo](https://github.com/batin/MacScores)
[site](https://batin.github.io/MacScores/)
