### ISSUE TITLE
bug in rewriting href links

### ISSUE THREAD

**Issue by derekphilipau** [KieferSivitz/vue-gh-pages#3]
In index.js, line 57, wrong var being used, resulting in href links not working properly:

`fs.writeFile('docs/index.html', newValue, 'utf-8', function (err) {`

Should be:

`fs.writeFile('docs/index.html', newValue2, 'utf-8', function (err) {`

**Comment by KieferSivitz** [comment]
Yes, yes it should. This is now fixed in 1.6.3, thank you!
