### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jlaustill** [KieferSivitz/vue-gh-pages#5]
How does this work for SEO?  Does github pages automatically compile and send to fastly?

**Comment by KieferSivitz** [comment]
As far as I'm aware this shouldn't mess with SEO any more than the vue-cli
build script does on it's own. The only modifications I make to the
index.html after the build is removing leading '/' from src and href tags.

I'm not sure I understand the 2nd question, but the script should
automatically deploy the new build so long as the homepage field is
included in the package.json. After which no additional action should be
required from you before the site is updated with the new build. It may
however take a few minutes, I'm not sure how often gh-pages updates their
cached version of a site. (I think it is every 10 minutes but I'm not all
that positive)
